name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build Application .jar
      working-directory: ./
      run: mvn clean package


    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build


    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:${{ github.run_id }}

